import { useState } from 'react';
import { UploadOutlined, WarningOutlined, ArrowLeftOutlined } from '@ant-design/icons';
import { Typography, Button, Card, Space, theme as antdTheme, Progress, Alert, Divider } from 'antd';

import { useDeviceManager } from '../../context/useDeviceManager';
import { SerialPortInfo } from '../../types/electron';

const { Text, Title } = Typography;

interface FlasherScreenProps {
    port: SerialPortInfo;
    onSuccess: () => void;
    onCancel: () => void;
}

export const FlasherScreen = ({ port, onSuccess, onCancel }: FlasherScreenProps) => {
    const { token } = antdTheme.useToken();
    const { isFlashing, flashProgress, selectFirmwareFile, flashDevice } = useDeviceManager();

    // State for all three required files
    const [bootloaderPath, setBootloaderPath] = useState<string | null>(null);
    const [partitionsPath, setPartitionsPath] = useState<string | null>(null);
    const [firmwarePath, setFirmwarePath] = useState<string | null>(null);

    const [flashScreenError, setFlashScreenError] = useState<string | null>(null);

    /**
     * Generic handler to open file dialog and set state
     */
    const handleSelectFile = async (setter: (path: string | null) => void) => {
        const path = await selectFirmwareFile(); // Reusing the existing dialog opener
        if (path) {
            setter(path);
        }
    };

    /**
     * Handles the 'Flash' button click.
     */
    const handleFlash = async () => {
        if (!port || !firmwarePath || !bootloaderPath || !partitionsPath) return;

        setFlashScreenError(null);

        try {
            // Note: You must update your useDeviceManager context and preload.ts
            // to accept this object structure if you haven't already.
            await flashDevice(port.path, {
                firmwarePath,
                bootloaderPath,
                partitionsPath,
            });
            onSuccess();
        } catch (err: any) {
            setFlashScreenError(err.message || 'An unknown flash error occurred.');
        }
    };

    // Helper to render a file selection row
    const renderFileSelector = (
        label: string,
        path: string | null,
        setter: (p: string | null) => void,
        placeholder: string
    ) => {
        const displayPath = path ? '...' + path.substring(Math.max(0, path.length - 40)) : placeholder;

        return (
            <div style={{ marginBottom: 12 }}>
                <Text strong style={{ display: 'block', marginBottom: 4 }}>
                    {label}
                </Text>
                <Space.Compact style={{ width: '100%' }}>
                    <Button icon={<UploadOutlined />} onClick={() => handleSelectFile(setter)} disabled={isFlashing}>
                        Select
                    </Button>
                    <Text
                        code
                        ellipsis
                        style={{
                            padding: '4px 11px',
                            border: `1px solid ${token.colorBorder}`,
                            borderRadius: `0 ${token.borderRadius}px ${token.borderRadius}px 0`,
                            background: token.colorBgContainer,
                            width: '100%',
                            color: path ? token.colorText : token.colorTextPlaceholder,
                        }}
                    >
                        {displayPath}
                    </Text>
                </Space.Compact>
            </div>
        );
    };

    const allFilesSelected = !!bootloaderPath && !!partitionsPath && !!firmwarePath;

    return (
        <div>
            <Button
                type="link"
                icon={<ArrowLeftOutlined />}
                onClick={onCancel}
                style={{ paddingLeft: 0, marginBottom: 16, display: 'block' }}
                disabled={isFlashing}
            >
                Back to Device List
            </Button>

            <Title level={5}>Flash Firmware</Title>
            <Text type="secondary">Select the three required binary files generated by PlatformIO.</Text>

            <Card
                size="small"
                style={{
                    width: '100%',
                    background: token.colorFillAlter,
                    marginTop: 12,
                }}
            >
                <Space direction="vertical" style={{ width: '100%' }}>
                    {renderFileSelector(
                        '1. Bootloader (bootloader.bin)',
                        bootloaderPath,
                        setBootloaderPath,
                        'Select bootloader.bin...'
                    )}

                    {renderFileSelector(
                        '2. Partitions (partitions.bin)',
                        partitionsPath,
                        setPartitionsPath,
                        'Select partitions.bin...'
                    )}

                    {renderFileSelector(
                        '3. Firmware (firmware.bin)',
                        firmwarePath,
                        setFirmwarePath,
                        'Select firmware.bin...'
                    )}

                    <Divider style={{ margin: '12px 0' }} />

                    {isFlashing && <Progress percent={flashProgress} status="active" strokeColor={token.colorInfo} />}

                    {flashScreenError && (
                        <Alert
                            message="Flash Failed"
                            description={flashScreenError}
                            type="error"
                            showIcon
                            closable
                            onClose={() => setFlashScreenError(null)}
                        />
                    )}

                    {!allFilesSelected && !isFlashing && (
                        <Alert
                            message="Missing Files"
                            description="Please select all three files to proceed."
                            type="info"
                            showIcon
                            style={{ marginBottom: 10 }}
                        />
                    )}

                    <Button
                        type="primary"
                        danger
                        icon={!isFlashing && <WarningOutlined />}
                        onClick={handleFlash}
                        loading={isFlashing}
                        disabled={!allFilesSelected || isFlashing}
                        style={{ width: '100%' }}
                    >
                        {isFlashing ? 'Flashing Device...' : 'Flash Device'}
                    </Button>
                </Space>
            </Card>
        </div>
    );
};
